### ISSUE TITLE
Why not alternative installer?

### ISSUE THREAD

**Issue by bam80** [firecat53/nixos#1]
https://github.com/firecat53/nixos/blob/d1b36ed9b4b0356763bc1d0551c9116114a37ae3/README.md?plain=1#L41-L60
Why don't you generate your custom unattended installer image instead, capable to do partitioning/formatting/mounting things?
That would allow to avoid the imperative part of the installation.

Corresponding projects I'm aware of:
https://github.com/nix-community/disko/blob/master/docs/disko-install.md#using-disko-install-in-an-offline-installer
https://github.com/NiklasGollenstede/nixos-installer
https://github.com/nix-community/nixos-anywhere

See also:
https://discourse.nixos.org/t/cloud-init-unattended-install/39149

**Comment by firecat53** [comment]
If I were having to install more often I would look into doing something like that. However, this README is more a reference for me if I have to reinstall one of my whopping 4 or 5 different machines. The goal is to not have to reinstall for a long time!

I still need to migrate my two primary machines to disko. Not excited about doing that because of downtime for heavily used family services...

Thanks for the input!
